[package]
name = "mtime"
description = "Unix time like library on Rust"
authors = ["ArZarLordOfMango", "Nebagibuappu"]
version = "1.1.4"

[lib]
name = "mtime"

[[test]]
name = "mtime"
path = "tests/test.rs"

[dependencies]
